import type { Agent, AgentActivity } from "@/lib/types";

export const agents: Agent[] = [
  {
    id: "agent-monitor",
    name: "Lead Monitor Agent",
    type: "monitor",
    status: "active",
    description: "Watches for new inbound leads across all connected sources",
    lastAction: "New lead detected from LinkedIn: Arjun Nair at Freshworks",
    lastActionAt: "2026-04-17T08:40:00Z",
    actionsToday: 23,
    icon: "Eye",
  },
  {
    id: "agent-classifier",
    name: "Classifier Agent",
    type: "classifier",
    status: "active",
    description: "Scores and categorizes leads using AI analysis",
    lastAction: "Scored Lead — TechNova Solutions: Hot (87/100)",
    lastActionAt: "2026-04-17T07:55:00Z",
    actionsToday: 47,
    icon: "Brain",
  },
  {
    id: "agent-outreach",
    name: "Outreach Agent",
    type: "outreach",
    status: "idle",
    description: "Drafts personalized emails and manages outreach sequences",
    lastAction:
      "Email draft created for Meera Kapoor — Subject: Partnership Opportunity",
    lastActionAt: "2026-04-17T07:20:00Z",
    actionsToday: 12,
    icon: "Mail",
  },
  {
    id: "agent-risk",
    name: "Risk Detector Agent",
    type: "risk",
    status: "active",
    description: "Flags leads showing signs of going cold or at-risk deals",
    lastAction: "⚠️ Flagged CloudMatrix — No response in 14 days",
    lastActionAt: "2026-04-17T06:45:00Z",
    actionsToday: 8,
    icon: "ShieldAlert",
  },
  {
    id: "agent-research",
    name: "Research Agent",
    type: "research",
    status: "idle",
    description: "Enriches lead profiles with company data and market intelligence",
    lastAction: "Enriched profile: DataVault Inc — Found Series B ($18M)",
    lastActionAt: "2026-04-17T06:10:00Z",
    actionsToday: 15,
    icon: "Search",
  },
];

export const agentActivityLog: AgentActivity[] = [
  {
    id: "activity-001",
    agentId: "agent-monitor",
    action: "New lead detected",
    detail: "New lead detected from LinkedIn: Arjun Nair at Freshworks",
    leadId: "lead-001",
    timestamp: "2026-04-17T08:35:00Z",
  },
  {
    id: "activity-002",
    agentId: "agent-classifier",
    action: "Lead scored",
    detail: "Scored Meera Kapoor — Hot (87/100)",
    leadId: "lead-003",
    timestamp: "2026-04-17T08:20:00Z",
  },
  {
    id: "activity-003",
    agentId: "agent-outreach",
    action: "Email draft created",
    detail: "Email draft created for Emily Carter — Subject: Growth partnership",
    leadId: "lead-002",
    timestamp: "2026-04-17T07:58:00Z",
  },
  {
    id: "activity-004",
    agentId: "agent-risk",
    action: "Risk flagged",
    detail: "⚠️ Flagged CloudMatrix — No response in 14 days",
    leadId: "lead-004",
    timestamp: "2026-04-17T07:40:00Z",
  },
  {
    id: "activity-005",
    agentId: "agent-research",
    action: "Profile enriched",
    detail: "Enriched profile: VertexForge — Found Series A ($12M)",
    leadId: "lead-013",
    timestamp: "2026-04-17T07:25:00Z",
  },
  {
    id: "activity-006",
    agentId: "agent-outreach",
    action: "Follow-up queued",
    detail: "Follow-up email queued for Sofia Martinez",
    leadId: "lead-005",
    timestamp: "2026-04-17T07:10:00Z",
  },
  {
    id: "activity-007",
    agentId: "agent-classifier",
    action: "Lead scored",
    detail: "Scored Grace Kim — Hot (79/100)",
    leadId: "lead-009",
    timestamp: "2026-04-17T06:55:00Z",
  },
  {
    id: "activity-008",
    agentId: "agent-research",
    action: "Company update",
    detail: "Company update: NovaLink AI raised $10M Series A",
    leadId: "lead-020",
    timestamp: "2026-04-17T06:40:00Z",
  },
  {
    id: "activity-009",
    agentId: "agent-risk",
    action: "Risk flagged",
    detail: "⚠️ Flagged Apex Logistics — Budget concern raised",
    leadId: "lead-016",
    timestamp: "2026-04-17T06:25:00Z",
  },
  {
    id: "activity-010",
    agentId: "agent-monitor",
    action: "New lead detected",
    detail: "New lead detected from Google Ads: Isabelle Laurent at HelixWorks",
    leadId: "lead-007",
    timestamp: "2026-04-17T06:10:00Z",
  },
  {
    id: "activity-011",
    agentId: "agent-outreach",
    action: "Email draft created",
    detail: "Email draft created for Nikhil Sharma — Subject: API integration",
    leadId: "lead-008",
    timestamp: "2026-04-17T05:55:00Z",
  },
  {
    id: "activity-012",
    agentId: "agent-classifier",
    action: "Lead scored",
    detail: "Scored Liam O'Connor — Cold (22/100)",
    leadId: "lead-012",
    timestamp: "2026-04-17T05:40:00Z",
  },
  {
    id: "activity-013",
    agentId: "agent-research",
    action: "Profile enriched",
    detail: "Enriched profile: Harborline — Found new APAC expansion",
    leadId: "lead-012",
    timestamp: "2026-04-17T05:25:00Z",
  },
  {
    id: "activity-014",
    agentId: "agent-risk",
    action: "Risk flagged",
    detail: "⚠️ Flagged SkyBridge Systems — Budget concern raised",
    leadId: "lead-017",
    timestamp: "2026-04-17T05:10:00Z",
  },
  {
    id: "activity-015",
    agentId: "agent-monitor",
    action: "Lead moved stage",
    detail: "Lead Marcus Lee moved from contacted to qualified",
    leadId: "lead-013",
    timestamp: "2026-04-17T04:55:00Z",
  },
  {
    id: "activity-016",
    agentId: "agent-outreach",
    action: "Follow-up queued",
    detail: "Follow-up email queued for Daniel Wu",
    leadId: "lead-004",
    timestamp: "2026-04-17T04:40:00Z",
  },
  {
    id: "activity-017",
    agentId: "agent-research",
    action: "Company update",
    detail: "Company update: PolarShift secured $6M seed funding",
    leadId: "lead-026",
    timestamp: "2026-04-17T04:25:00Z",
  },
  {
    id: "activity-018",
    agentId: "agent-classifier",
    action: "Lead scored",
    detail: "Scored Chloe Bennett — Warm (64/100)",
    leadId: "lead-031",
    timestamp: "2026-04-17T04:10:00Z",
  },
  {
    id: "activity-019",
    agentId: "agent-monitor",
    action: "Lead moved stage",
    detail: "Lead Rhea Menon moved from proposal to negotiation",
    leadId: "lead-033",
    timestamp: "2026-04-17T03:55:00Z",
  },
  {
    id: "activity-020",
    agentId: "agent-outreach",
    action: "Email draft created",
    detail: "Email draft created for Julia Stein — Subject: Partnership plan",
    leadId: "lead-015",
    timestamp: "2026-04-17T03:40:00Z",
  },
  {
    id: "activity-021",
    agentId: "agent-risk",
    action: "Risk flagged",
    detail: "⚠️ Flagged ProtoLabs — Decision maker changed",
    leadId: "lead-034",
    timestamp: "2026-04-17T03:25:00Z",
  },
  {
    id: "activity-022",
    agentId: "agent-research",
    action: "Profile enriched",
    detail: "Enriched profile: Lumina Health — Added HIPAA compliance notes",
    leadId: "lead-010",
    timestamp: "2026-04-17T03:10:00Z",
  },
  {
    id: "activity-023",
    agentId: "agent-monitor",
    action: "New lead detected",
    detail: "New lead detected from referral: Peter Collins at AnchorPoint",
    leadId: "lead-021",
    timestamp: "2026-04-17T02:55:00Z",
  },
  {
    id: "activity-024",
    agentId: "agent-classifier",
    action: "Lead scored",
    detail: "Scored Hannah Lee — Cold (26/100)",
    leadId: "lead-019",
    timestamp: "2026-04-17T02:40:00Z",
  },
  {
    id: "activity-025",
    agentId: "agent-outreach",
    action: "Follow-up queued",
    detail: "Follow-up email queued for Oliver Hughes",
    leadId: "lead-017",
    timestamp: "2026-04-17T02:25:00Z",
  },
  {
    id: "activity-026",
    agentId: "agent-research",
    action: "Company update",
    detail: "Company update: BrightStack opened new APAC office",
    leadId: "lead-019",
    timestamp: "2026-04-17T02:10:00Z",
  },
  {
    id: "activity-027",
    agentId: "agent-risk",
    action: "Lead temperature changed",
    detail: "Lead Aisha Khan moved from warm to cold",
    leadId: "lead-050",
    timestamp: "2026-04-17T01:55:00Z",
  },
  {
    id: "activity-028",
    agentId: "agent-monitor",
    action: "Lead moved stage",
    detail: "Lead Noah Parker moved from proposal to negotiation",
    leadId: "lead-028",
    timestamp: "2026-04-17T01:40:00Z",
  },
  {
    id: "activity-029",
    agentId: "agent-outreach",
    action: "Email draft created",
    detail: "Email draft created for Haruki Sato — Subject: ROI summary",
    leadId: "lead-044",
    timestamp: "2026-04-17T01:25:00Z",
  },
  {
    id: "activity-030",
    agentId: "agent-classifier",
    action: "Lead scored",
    detail: "Scored Samantha Quinn — Hot (80/100)",
    leadId: "lead-045",
    timestamp: "2026-04-17T01:10:00Z",
  },
];
