import type { Lead } from "@/lib/types";

export const leads: Lead[] = [
  {
    id: "lead-001",
    name: "Arjun Nair",
    email: "arjun.nair@freshworks.com",
    company: "Freshworks",
    title: "Director of RevOps",
    phone: "+91 98765 11001",
    source: "linkedin",
    stage: "new",
    score: 42,
    temperature: "warm",
    assignedTo: "user-1",
    createdAt: "2026-04-06",
    lastActivityAt: "2026-04-15",
    nextFollowUp: "2026-04-18",
    tags: ["SaaS", "inbound"],
    notes: ["Requested pricing sheet."],
    emailsSent: 1,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.42,
    value: 42000,
  },
  {
    id: "lead-002",
    name: "Emily Carter",
    email: "emily.carter@northwindmedia.com",
    company: "Northwind Media",
    title: "Head of Growth",
    phone: "+1 415-555-2202",
    source: "google_ads",
    stage: "contacted",
    score: 35,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-03-28",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-17",
    tags: ["ads", "mid-market"],
    notes: ["Downloaded case study."],
    emailsSent: 2,
    emailsOpened: 2,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 12,
    riskFlag: false,
    predictedWinProbability: 0.33,
    value: 28000,
  },
  {
    id: "lead-003",
    name: "Meera Kapoor",
    email: "meera.kapoor@technova.io",
    company: "TechNova Solutions",
    title: "VP Sales",
    phone: "+91 98765 22310",
    source: "webinar",
    stage: "qualified",
    score: 87,
    temperature: "hot",
    assignedTo: "user-3",
    createdAt: "2026-03-25",
    lastActivityAt: "2026-04-16",
    nextFollowUp: "2026-04-20",
    tags: ["enterprise", "webinar"],
    notes: ["Asked for proposal by Friday."],
    emailsSent: 3,
    emailsOpened: 3,
    emailsReplied: 2,
    callsMade: 2,
    callsDuration: 48,
    riskFlag: false,
    predictedWinProbability: 0.78,
    value: 120000,
  },
  {
    id: "lead-004",
    name: "Daniel Wu",
    email: "daniel.wu@cloudmatrix.io",
    company: "CloudMatrix",
    title: "Operations Lead",
    phone: "+1 408-555-0144",
    source: "referral",
    stage: "contacted",
    score: 28,
    temperature: "cold",
    assignedTo: "user-1",
    createdAt: "2026-03-30",
    lastActivityAt: "2026-04-11",
    nextFollowUp: "2026-04-16",
    tags: ["referral"],
    notes: ["Waiting on internal buy-in."],
    emailsSent: 4,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 9,
    riskFlag: true,
    riskReason: "No response in 14 days",
    predictedWinProbability: 0.18,
    value: 18000,
  },
  {
    id: "lead-005",
    name: "Sofia Martinez",
    email: "sofia@aetherfinance.com",
    company: "Aether Finance",
    title: "Head of Partnerships",
    phone: "+44 20 7946 5541",
    source: "linkedin",
    stage: "proposal",
    score: 74,
    temperature: "hot",
    assignedTo: "user-2",
    createdAt: "2026-03-22",
    lastActivityAt: "2026-04-13",
    nextFollowUp: "2026-04-19",
    tags: ["fintech", "priority"],
    notes: ["Proposal reviewed by finance."],
    emailsSent: 5,
    emailsOpened: 4,
    emailsReplied: 2,
    callsMade: 3,
    callsDuration: 62,
    riskFlag: false,
    predictedWinProbability: 0.66,
    value: 95000,
  },
  {
    id: "lead-006",
    name: "Karan Bhatia",
    email: "karan.bhatia@zenlayer.in",
    company: "ZenLayer India",
    title: "Sales Manager",
    phone: "+91 98111 44221",
    source: "cold_outreach",
    stage: "new",
    score: 18,
    temperature: "cold",
    assignedTo: "user-3",
    createdAt: "2026-04-10",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-15",
    tags: ["outbound"],
    notes: ["Initial cold email sent."],
    emailsSent: 1,
    emailsOpened: 0,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: true,
    riskReason: "No response in 14 days",
    predictedWinProbability: 0.12,
    value: 9000,
  },
  {
    id: "lead-007",
    name: "Isabelle Laurent",
    email: "isabelle@helixworks.fr",
    company: "HelixWorks",
    title: "Chief of Staff",
    phone: "+33 1 44 55 77 82",
    source: "google_ads",
    stage: "new",
    score: 39,
    temperature: "warm",
    assignedTo: "user-1",
    createdAt: "2026-04-03",
    lastActivityAt: "2026-04-14",
    nextFollowUp: "2026-04-17",
    tags: ["europe", "inbound"],
    notes: ["Requested demo slots."],
    emailsSent: 1,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.36,
    value: 36000,
  },
  {
    id: "lead-008",
    name: "Nikhil Sharma",
    email: "nikhil@orbitpay.in",
    company: "OrbitPay",
    title: "Product Lead",
    phone: "+91 99671 55210",
    source: "linkedin",
    stage: "contacted",
    score: 44,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-03-31",
    lastActivityAt: "2026-04-15",
    nextFollowUp: "2026-04-21",
    tags: ["fintech"],
    notes: ["Shared integration checklist."],
    emailsSent: 2,
    emailsOpened: 2,
    emailsReplied: 1,
    callsMade: 1,
    callsDuration: 18,
    riskFlag: false,
    predictedWinProbability: 0.41,
    value: 52000,
  },
  {
    id: "lead-009",
    name: "Grace Kim",
    email: "grace.kim@synergyops.ai",
    company: "SynergyOps",
    title: "COO",
    phone: "+1 646-555-5509",
    source: "webinar",
    stage: "qualified",
    score: 79,
    temperature: "hot",
    assignedTo: "user-3",
    createdAt: "2026-03-24",
    lastActivityAt: "2026-04-17",
    nextFollowUp: "2026-04-23",
    tags: ["AI", "enterprise"],
    notes: ["Wants pilot in May."],
    emailsSent: 4,
    emailsOpened: 3,
    emailsReplied: 2,
    callsMade: 2,
    callsDuration: 44,
    riskFlag: false,
    predictedWinProbability: 0.71,
    value: 140000,
  },
  {
    id: "lead-010",
    name: "Abigail Brooks",
    email: "abigail@luminahealth.com",
    company: "Lumina Health",
    title: "Head of Sales Ops",
    phone: "+1 312-555-0291",
    source: "referral",
    stage: "proposal",
    score: 68,
    temperature: "hot",
    assignedTo: "user-1",
    createdAt: "2026-03-21",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-18",
    tags: ["healthcare"],
    notes: ["Legal review in progress."],
    emailsSent: 5,
    emailsOpened: 4,
    emailsReplied: 2,
    callsMade: 2,
    callsDuration: 35,
    riskFlag: false,
    predictedWinProbability: 0.63,
    value: 88000,
  },
  {
    id: "lead-011",
    name: "Devika Rao",
    email: "devika@quantshelf.in",
    company: "QuantShelf",
    title: "Head of Revenue",
    phone: "+91 98223 44120",
    source: "linkedin",
    stage: "contacted",
    score: 31,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-04-02",
    lastActivityAt: "2026-04-13",
    nextFollowUp: "2026-04-16",
    tags: ["fintech"],
    notes: ["Interested in AI scoring."],
    emailsSent: 2,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 10,
    riskFlag: false,
    predictedWinProbability: 0.29,
    value: 30000,
  },
  {
    id: "lead-012",
    name: "Liam O'Connor",
    email: "liam@harborline.io",
    company: "Harborline",
    title: "Director of Sales",
    phone: "+353 1 234 8801",
    source: "google_ads",
    stage: "new",
    score: 22,
    temperature: "cold",
    assignedTo: "user-3",
    createdAt: "2026-04-09",
    lastActivityAt: "2026-04-11",
    nextFollowUp: "2026-04-14",
    tags: ["EMEA"],
    notes: ["Booked intro, no response after."],
    emailsSent: 1,
    emailsOpened: 0,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: true,
    riskReason: "No response in 14 days",
    predictedWinProbability: 0.14,
    value: 15000,
  },
  {
    id: "lead-013",
    name: "Marcus Lee",
    email: "marcus@vertexforge.com",
    company: "VertexForge",
    title: "Revenue Operations",
    phone: "+1 206-555-4408",
    source: "webinar",
    stage: "qualified",
    score: 72,
    temperature: "hot",
    assignedTo: "user-1",
    createdAt: "2026-03-20",
    lastActivityAt: "2026-04-16",
    nextFollowUp: "2026-04-21",
    tags: ["SaaS", "webinar"],
    notes: ["Needs security documentation."],
    emailsSent: 3,
    emailsOpened: 3,
    emailsReplied: 1,
    callsMade: 2,
    callsDuration: 38,
    riskFlag: false,
    predictedWinProbability: 0.6,
    value: 76000,
  },
  {
    id: "lead-014",
    name: "Sanjana Gupta",
    email: "sanjana@elevateai.in",
    company: "ElevateAI",
    title: "Head of Marketing",
    phone: "+91 99201 11090",
    source: "linkedin",
    stage: "new",
    score: 33,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-04-05",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-17",
    tags: ["marketing"],
    notes: ["Requested feature list."],
    emailsSent: 1,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.31,
    value: 26000,
  },
  {
    id: "lead-015",
    name: "Julia Stein",
    email: "julia.stein@dataforge.ai",
    company: "DataForge",
    title: "VP Partnerships",
    phone: "+49 30 5566 221",
    source: "google_ads",
    stage: "contacted",
    score: 47,
    temperature: "warm",
    assignedTo: "user-3",
    createdAt: "2026-03-29",
    lastActivityAt: "2026-04-17",
    nextFollowUp: "2026-04-22",
    tags: ["AI", "mid-market"],
    notes: ["Looking for co-sell strategy."],
    emailsSent: 3,
    emailsOpened: 2,
    emailsReplied: 1,
    callsMade: 1,
    callsDuration: 14,
    riskFlag: false,
    predictedWinProbability: 0.46,
    value: 54000,
  },
  {
    id: "lead-016",
    name: "Rohit Verma",
    email: "rohit@apexlogistics.in",
    company: "Apex Logistics",
    title: "Operations Director",
    phone: "+91 98450 31120",
    source: "referral",
    stage: "qualified",
    score: 63,
    temperature: "warm",
    assignedTo: "user-1",
    createdAt: "2026-03-27",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-18",
    tags: ["logistics"],
    notes: ["Requested pricing tier details."],
    emailsSent: 3,
    emailsOpened: 2,
    emailsReplied: 1,
    callsMade: 2,
    callsDuration: 30,
    riskFlag: false,
    predictedWinProbability: 0.52,
    value: 68000,
  },
  {
    id: "lead-017",
    name: "Oliver Hughes",
    email: "oliver@skybridge.com",
    company: "SkyBridge Systems",
    title: "Head of Growth",
    phone: "+1 212-555-8819",
    source: "linkedin",
    stage: "proposal",
    score: 70,
    temperature: "hot",
    assignedTo: "user-2",
    createdAt: "2026-03-19",
    lastActivityAt: "2026-04-11",
    nextFollowUp: "2026-04-19",
    tags: ["enterprise"],
    notes: ["Needs CFO sign-off."],
    emailsSent: 4,
    emailsOpened: 4,
    emailsReplied: 2,
    callsMade: 3,
    callsDuration: 52,
    riskFlag: true,
    riskReason: "Budget concern raised",
    predictedWinProbability: 0.58,
    value: 105000,
  },
  {
    id: "lead-018",
    name: "Priyanka Malhotra",
    email: "priyanka@harborcloud.io",
    company: "HarborCloud",
    title: "Sales Ops Manager",
    phone: "+91 98990 77654",
    source: "webinar",
    stage: "contacted",
    score: 37,
    temperature: "warm",
    assignedTo: "user-3",
    createdAt: "2026-04-01",
    lastActivityAt: "2026-04-14",
    nextFollowUp: "2026-04-17",
    tags: ["cloud"],
    notes: ["Awaiting demo recording."],
    emailsSent: 2,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 11,
    riskFlag: false,
    predictedWinProbability: 0.35,
    value: 32000,
  },
  {
    id: "lead-019",
    name: "Hannah Lee",
    email: "hannah@brightstack.io",
    company: "BrightStack",
    title: "Revenue Manager",
    phone: "+61 2 5550 9981",
    source: "google_ads",
    stage: "new",
    score: 26,
    temperature: "cold",
    assignedTo: "user-1",
    createdAt: "2026-04-08",
    lastActivityAt: "2026-04-13",
    nextFollowUp: "2026-04-16",
    tags: ["APAC"],
    notes: ["Initial response pending."],
    emailsSent: 1,
    emailsOpened: 0,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.21,
    value: 19000,
  },
  {
    id: "lead-020",
    name: "Aditi Chawla",
    email: "aditi@novalink.ai",
    company: "NovaLink AI",
    title: "Co-Founder",
    phone: "+91 98770 22110",
    source: "linkedin",
    stage: "qualified",
    score: 81,
    temperature: "hot",
    assignedTo: "user-2",
    createdAt: "2026-03-23",
    lastActivityAt: "2026-04-16",
    nextFollowUp: "2026-04-20",
    tags: ["startup", "AI"],
    notes: ["Requested enterprise security docs."],
    emailsSent: 3,
    emailsOpened: 3,
    emailsReplied: 2,
    callsMade: 2,
    callsDuration: 40,
    riskFlag: false,
    predictedWinProbability: 0.74,
    value: 98000,
  },
  {
    id: "lead-021",
    name: "Peter Collins",
    email: "peter@anchorpoint.com",
    company: "AnchorPoint Logistics",
    title: "VP Operations",
    phone: "+1 512-555-6401",
    source: "referral",
    stage: "contacted",
    score: 46,
    temperature: "warm",
    assignedTo: "user-3",
    createdAt: "2026-03-26",
    lastActivityAt: "2026-04-10",
    nextFollowUp: "2026-04-15",
    tags: ["logistics"],
    notes: ["Wants call with CTO."],
    emailsSent: 2,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 15,
    riskFlag: false,
    predictedWinProbability: 0.4,
    value: 45000,
  },
  {
    id: "lead-022",
    name: "Sophie Nguyen",
    email: "sophie@orionlabs.io",
    company: "Orion Labs",
    title: "Head of Revenue",
    phone: "+1 213-555-7102",
    source: "webinar",
    stage: "proposal",
    score: 69,
    temperature: "hot",
    assignedTo: "user-1",
    createdAt: "2026-03-18",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-19",
    tags: ["SaaS", "pipeline"],
    notes: ["Negotiating annual terms."],
    emailsSent: 4,
    emailsOpened: 3,
    emailsReplied: 2,
    callsMade: 2,
    callsDuration: 33,
    riskFlag: false,
    predictedWinProbability: 0.61,
    value: 92000,
  },
  {
    id: "lead-023",
    name: "Kabir Iyer",
    email: "kabir@fluxgrid.in",
    company: "FluxGrid",
    title: "Business Development",
    phone: "+91 98765 33441",
    source: "linkedin",
    stage: "new",
    score: 40,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-04-07",
    lastActivityAt: "2026-04-15",
    nextFollowUp: "2026-04-18",
    tags: ["energy"],
    notes: ["Asked for integration details."],
    emailsSent: 1,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.37,
    value: 36000,
  },
  {
    id: "lead-024",
    name: "Maria Rossi",
    email: "maria@piersystems.it",
    company: "Pier Systems",
    title: "Commercial Director",
    phone: "+39 06 3321 441",
    source: "google_ads",
    stage: "contacted",
    score: 34,
    temperature: "warm",
    assignedTo: "user-3",
    createdAt: "2026-03-30",
    lastActivityAt: "2026-04-13",
    nextFollowUp: "2026-04-17",
    tags: ["EMEA"],
    notes: ["Waiting on internal sponsor."],
    emailsSent: 2,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 9,
    riskFlag: false,
    predictedWinProbability: 0.3,
    value: 31000,
  },
  {
    id: "lead-025",
    name: "Ishita Kulkarni",
    email: "ishita@vertexlabs.in",
    company: "Vertex Labs",
    title: "Head of Customer Success",
    phone: "+91 98200 44562",
    source: "webinar",
    stage: "qualified",
    score: 58,
    temperature: "warm",
    assignedTo: "user-1",
    createdAt: "2026-03-28",
    lastActivityAt: "2026-04-11",
    nextFollowUp: "2026-04-18",
    tags: ["customer-success"],
    notes: ["Needs onboarding timeline."],
    emailsSent: 3,
    emailsOpened: 2,
    emailsReplied: 1,
    callsMade: 1,
    callsDuration: 22,
    riskFlag: false,
    predictedWinProbability: 0.49,
    value: 57000,
  },
  {
    id: "lead-026",
    name: "George Adams",
    email: "george@polarshift.ai",
    company: "PolarShift",
    title: "VP Growth",
    phone: "+1 718-555-7721",
    source: "google_ads",
    stage: "contacted",
    score: 41,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-04-01",
    lastActivityAt: "2026-04-10",
    nextFollowUp: "2026-04-15",
    tags: ["ads"],
    notes: ["Requested product video."],
    emailsSent: 2,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.34,
    value: 34000,
  },
  {
    id: "lead-027",
    name: "Anita Desai",
    email: "anita@reefcommerce.in",
    company: "Reef Commerce",
    title: "Sales Director",
    phone: "+91 90010 45211",
    source: "referral",
    stage: "proposal",
    score: 62,
    temperature: "warm",
    assignedTo: "user-3",
    createdAt: "2026-03-20",
    lastActivityAt: "2026-04-14",
    nextFollowUp: "2026-04-19",
    tags: ["commerce"],
    notes: ["Waiting on procurement."],
    emailsSent: 4,
    emailsOpened: 3,
    emailsReplied: 1,
    callsMade: 2,
    callsDuration: 28,
    riskFlag: true,
    riskReason: "Contract stalled for 3 weeks",
    predictedWinProbability: 0.44,
    value: 61000,
  },
  {
    id: "lead-028",
    name: "Noah Parker",
    email: "noah@stellarcore.com",
    company: "StellarCore",
    title: "Head of Sales",
    phone: "+1 646-555-3348",
    source: "linkedin",
    stage: "negotiation",
    score: 76,
    temperature: "hot",
    assignedTo: "user-1",
    createdAt: "2026-03-18",
    lastActivityAt: "2026-04-16",
    nextFollowUp: "2026-04-18",
    tags: ["enterprise"],
    notes: ["Pricing negotiation underway."],
    emailsSent: 5,
    emailsOpened: 4,
    emailsReplied: 2,
    callsMade: 4,
    callsDuration: 70,
    riskFlag: false,
    predictedWinProbability: 0.7,
    value: 130000,
  },
  {
    id: "lead-029",
    name: "Shreya Kulkarni",
    email: "shreya@zenpath.in",
    company: "ZenPath",
    title: "Product Marketing",
    phone: "+91 99230 55221",
    source: "webinar",
    stage: "contacted",
    score: 38,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-03-31",
    lastActivityAt: "2026-04-13",
    nextFollowUp: "2026-04-17",
    tags: ["marketing"],
    notes: ["Follow-up scheduled."],
    emailsSent: 2,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 12,
    riskFlag: false,
    predictedWinProbability: 0.33,
    value: 27000,
  },
  {
    id: "lead-030",
    name: "Miguel Torres",
    email: "miguel@atlaslight.com",
    company: "AtlasLight",
    title: "Revenue Ops Lead",
    phone: "+34 91 554 8881",
    source: "google_ads",
    stage: "new",
    score: 30,
    temperature: "warm",
    assignedTo: "user-3",
    createdAt: "2026-04-04",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-18",
    tags: ["EMEA"],
    notes: ["Signed up for newsletter."],
    emailsSent: 1,
    emailsOpened: 0,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.28,
    value: 24000,
  },
  {
    id: "lead-031",
    name: "Chloe Bennett",
    email: "chloe@pixelforge.io",
    company: "PixelForge",
    title: "Head of Partnerships",
    phone: "+1 503-555-1302",
    source: "linkedin",
    stage: "qualified",
    score: 64,
    temperature: "warm",
    assignedTo: "user-1",
    createdAt: "2026-03-26",
    lastActivityAt: "2026-04-15",
    nextFollowUp: "2026-04-20",
    tags: ["SaaS"],
    notes: ["Needs integration estimate."],
    emailsSent: 3,
    emailsOpened: 2,
    emailsReplied: 1,
    callsMade: 2,
    callsDuration: 34,
    riskFlag: false,
    predictedWinProbability: 0.55,
    value: 68000,
  },
  {
    id: "lead-032",
    name: "Tara Williams",
    email: "tara@medialoop.com",
    company: "MediaLoop",
    title: "Sales Enablement",
    phone: "+1 718-555-9032",
    source: "google_ads",
    stage: "contacted",
    score: 36,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-04-02",
    lastActivityAt: "2026-04-11",
    nextFollowUp: "2026-04-15",
    tags: ["media"],
    notes: ["Needs pricing for 50 seats."],
    emailsSent: 2,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 13,
    riskFlag: false,
    predictedWinProbability: 0.32,
    value: 41000,
  },
  {
    id: "lead-033",
    name: "Rhea Menon",
    email: "rhea@silvershift.in",
    company: "SilverShift",
    title: "Founder",
    phone: "+91 98901 66221",
    source: "referral",
    stage: "negotiation",
    score: 83,
    temperature: "hot",
    assignedTo: "user-3",
    createdAt: "2026-03-19",
    lastActivityAt: "2026-04-16",
    nextFollowUp: "2026-04-18",
    tags: ["startup", "priority"],
    notes: ["Finalizing annual contract."],
    emailsSent: 5,
    emailsOpened: 4,
    emailsReplied: 3,
    callsMade: 3,
    callsDuration: 58,
    riskFlag: false,
    predictedWinProbability: 0.81,
    value: 115000,
  },
  {
    id: "lead-034",
    name: "Victor Chen",
    email: "victor@protolabs.ai",
    company: "ProtoLabs",
    title: "Chief Revenue Officer",
    phone: "+1 646-555-3772",
    source: "webinar",
    stage: "proposal",
    score: 66,
    temperature: "warm",
    assignedTo: "user-1",
    createdAt: "2026-03-21",
    lastActivityAt: "2026-04-13",
    nextFollowUp: "2026-04-19",
    tags: ["enterprise"],
    notes: ["Contract review in progress."],
    emailsSent: 4,
    emailsOpened: 3,
    emailsReplied: 1,
    callsMade: 2,
    callsDuration: 29,
    riskFlag: true,
    riskReason: "Decision maker changed",
    predictedWinProbability: 0.5,
    value: 99000,
  },
  {
    id: "lead-035",
    name: "Jacob Holt",
    email: "jacob@cloudship.io",
    company: "CloudShip",
    title: "VP Sales",
    phone: "+1 312-555-4491",
    source: "linkedin",
    stage: "won",
    score: 88,
    temperature: "hot",
    assignedTo: "user-2",
    createdAt: "2026-03-18",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-20",
    tags: ["enterprise", "won"],
    notes: ["Signed annual contract."],
    emailsSent: 6,
    emailsOpened: 5,
    emailsReplied: 3,
    callsMade: 4,
    callsDuration: 75,
    riskFlag: false,
    predictedWinProbability: 0.92,
    value: 150000,
  },
  {
    id: "lead-036",
    name: "Esha Rao",
    email: "esha@blueridge.in",
    company: "BlueRidge Analytics",
    title: "Growth Lead",
    phone: "+91 98110 55231",
    source: "linkedin",
    stage: "qualified",
    score: 59,
    temperature: "warm",
    assignedTo: "user-3",
    createdAt: "2026-03-27",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-17",
    tags: ["analytics"],
    notes: ["Waiting on security review."],
    emailsSent: 3,
    emailsOpened: 2,
    emailsReplied: 1,
    callsMade: 1,
    callsDuration: 25,
    riskFlag: false,
    predictedWinProbability: 0.47,
    value: 56000,
  },
  {
    id: "lead-037",
    name: "Javier Perez",
    email: "javier@haloenergy.co",
    company: "Halo Energy",
    title: "VP Operations",
    phone: "+52 55 5510 8872",
    source: "google_ads",
    stage: "new",
    score: 21,
    temperature: "cold",
    assignedTo: "user-1",
    createdAt: "2026-04-07",
    lastActivityAt: "2026-04-10",
    nextFollowUp: "2026-04-15",
    tags: ["energy"],
    notes: ["Follow-up email sent."],
    emailsSent: 1,
    emailsOpened: 0,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.16,
    value: 22000,
  },
  {
    id: "lead-038",
    name: "Alyssa Brown",
    email: "alyssa@netwise.io",
    company: "Netwise",
    title: "Sales Director",
    phone: "+1 202-555-6678",
    source: "webinar",
    stage: "qualified",
    score: 67,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-03-24",
    lastActivityAt: "2026-04-16",
    nextFollowUp: "2026-04-21",
    tags: ["cloud"],
    notes: ["Requesting ROI model."],
    emailsSent: 3,
    emailsOpened: 2,
    emailsReplied: 1,
    callsMade: 2,
    callsDuration: 31,
    riskFlag: false,
    predictedWinProbability: 0.56,
    value: 72000,
  },
  {
    id: "lead-039",
    name: "Suresh Nambiar",
    email: "suresh@vertexwave.in",
    company: "VertexWave",
    title: "Chief of Staff",
    phone: "+91 99000 77661",
    source: "referral",
    stage: "negotiation",
    score: 77,
    temperature: "hot",
    assignedTo: "user-3",
    createdAt: "2026-03-20",
    lastActivityAt: "2026-04-14",
    nextFollowUp: "2026-04-19",
    tags: ["enterprise"],
    notes: ["Legal team reviewing MSA."],
    emailsSent: 4,
    emailsOpened: 3,
    emailsReplied: 2,
    callsMade: 3,
    callsDuration: 46,
    riskFlag: true,
    riskReason: "Contract stalled for 3 weeks",
    predictedWinProbability: 0.64,
    value: 118000,
  },
  {
    id: "lead-040",
    name: "Charlotte Evans",
    email: "charlotte@risegrid.co",
    company: "RiseGrid",
    title: "Head of Partnerships",
    phone: "+44 20 7555 9912",
    source: "linkedin",
    stage: "won",
    score: 90,
    temperature: "hot",
    assignedTo: "user-1",
    createdAt: "2026-03-18",
    lastActivityAt: "2026-04-11",
    nextFollowUp: "2026-04-20",
    tags: ["enterprise", "won"],
    notes: ["Kickoff scheduled."],
    emailsSent: 6,
    emailsOpened: 5,
    emailsReplied: 3,
    callsMade: 4,
    callsDuration: 68,
    riskFlag: false,
    predictedWinProbability: 0.95,
    value: 135000,
  },
  {
    id: "lead-041",
    name: "Manoj Kulkarni",
    email: "manoj@brightlane.in",
    company: "Brightlane",
    title: "Business Head",
    phone: "+91 98457 20021",
    source: "cold_outreach",
    stage: "contacted",
    score: 27,
    temperature: "cold",
    assignedTo: "user-2",
    createdAt: "2026-04-03",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-16",
    tags: ["outbound"],
    notes: ["Responded asking for brochure."],
    emailsSent: 2,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.22,
    value: 14000,
  },
  {
    id: "lead-042",
    name: "James Foster",
    email: "james@keystone.ai",
    company: "Keystone AI",
    title: "VP Revenue",
    phone: "+1 415-555-1901",
    source: "google_ads",
    stage: "new",
    score: 32,
    temperature: "warm",
    assignedTo: "user-3",
    createdAt: "2026-04-05",
    lastActivityAt: "2026-04-13",
    nextFollowUp: "2026-04-17",
    tags: ["AI"],
    notes: ["Downloaded playbook."],
    emailsSent: 1,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.29,
    value: 33000,
  },
  {
    id: "lead-043",
    name: "Neha Nair",
    email: "neha@pulsebridge.in",
    company: "PulseBridge",
    title: "Revenue Lead",
    phone: "+91 99887 11221",
    source: "webinar",
    stage: "qualified",
    score: 61,
    temperature: "warm",
    assignedTo: "user-1",
    createdAt: "2026-03-26",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-18",
    tags: ["healthtech"],
    notes: ["Needs CRM integration timeline."],
    emailsSent: 3,
    emailsOpened: 2,
    emailsReplied: 1,
    callsMade: 2,
    callsDuration: 27,
    riskFlag: false,
    predictedWinProbability: 0.52,
    value: 62000,
  },
  {
    id: "lead-044",
    name: "Haruki Sato",
    email: "haruki@zenbyte.jp",
    company: "ZenByte",
    title: "Commercial Manager",
    phone: "+81 3 5566 3388",
    source: "linkedin",
    stage: "proposal",
    score: 65,
    temperature: "warm",
    assignedTo: "user-2",
    createdAt: "2026-03-22",
    lastActivityAt: "2026-04-14",
    nextFollowUp: "2026-04-19",
    tags: ["APAC", "enterprise"],
    notes: ["Reviewing ROI model."],
    emailsSent: 4,
    emailsOpened: 3,
    emailsReplied: 1,
    callsMade: 2,
    callsDuration: 36,
    riskFlag: false,
    predictedWinProbability: 0.57,
    value: 89000,
  },
  {
    id: "lead-045",
    name: "Samantha Quinn",
    email: "samantha@evernorth.ai",
    company: "Evernorth AI",
    title: "Chief Strategy Officer",
    phone: "+1 646-555-3312",
    source: "webinar",
    stage: "negotiation",
    score: 80,
    temperature: "hot",
    assignedTo: "user-3",
    createdAt: "2026-03-21",
    lastActivityAt: "2026-04-15",
    nextFollowUp: "2026-04-18",
    tags: ["enterprise"],
    notes: ["Pricing discussion ongoing."],
    emailsSent: 5,
    emailsOpened: 4,
    emailsReplied: 2,
    callsMade: 3,
    callsDuration: 55,
    riskFlag: false,
    predictedWinProbability: 0.73,
    value: 125000,
  },
  {
    id: "lead-046",
    name: "Anil Joshi",
    email: "anil@gridline.in",
    company: "Gridline Systems",
    title: "Operations Head",
    phone: "+91 98123 77651",
    source: "cold_outreach",
    stage: "contacted",
    score: 20,
    temperature: "cold",
    assignedTo: "user-1",
    createdAt: "2026-04-06",
    lastActivityAt: "2026-04-11",
    nextFollowUp: "2026-04-15",
    tags: ["outbound"],
    notes: ["Follow-up pending."],
    emailsSent: 2,
    emailsOpened: 0,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: true,
    riskReason: "No response in 14 days",
    predictedWinProbability: 0.1,
    value: 8000,
  },
  {
    id: "lead-047",
    name: "Sophia Adler",
    email: "sophia@futurix.ai",
    company: "Futurix",
    title: "Head of Demand Gen",
    phone: "+1 415-555-8890",
    source: "google_ads",
    stage: "new",
    score: 29,
    temperature: "cold",
    assignedTo: "user-2",
    createdAt: "2026-04-04",
    lastActivityAt: "2026-04-13",
    nextFollowUp: "2026-04-17",
    tags: ["ads"],
    notes: ["Requested demo link."],
    emailsSent: 1,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: false,
    predictedWinProbability: 0.25,
    value: 21000,
  },
  {
    id: "lead-048",
    name: "Luca Bianchi",
    email: "luca@stridepay.it",
    company: "StridePay",
    title: "Head of Partnerships",
    phone: "+39 02 6677 113",
    source: "referral",
    stage: "won",
    score: 85,
    temperature: "hot",
    assignedTo: "user-3",
    createdAt: "2026-03-19",
    lastActivityAt: "2026-04-12",
    nextFollowUp: "2026-04-20",
    tags: ["fintech", "won"],
    notes: ["Implementation kickoff next week."],
    emailsSent: 6,
    emailsOpened: 5,
    emailsReplied: 3,
    callsMade: 4,
    callsDuration: 60,
    riskFlag: false,
    predictedWinProbability: 0.9,
    value: 145000,
  },
  {
    id: "lead-049",
    name: "Aarav Khanna",
    email: "aarav@opalsys.in",
    company: "Opal Systems",
    title: "Head of Sales",
    phone: "+91 99990 22112",
    source: "linkedin",
    stage: "lost",
    score: 14,
    temperature: "cold",
    assignedTo: "user-1",
    createdAt: "2026-03-18",
    lastActivityAt: "2026-04-10",
    nextFollowUp: "2026-04-14",
    tags: ["lost"],
    notes: ["Chose competitor."],
    emailsSent: 3,
    emailsOpened: 1,
    emailsReplied: 0,
    callsMade: 1,
    callsDuration: 8,
    riskFlag: true,
    riskReason: "Competitor mentioned in last call",
    predictedWinProbability: 0.08,
    value: 12000,
  },
  {
    id: "lead-050",
    name: "Aisha Khan",
    email: "aisha@signalbridge.in",
    company: "SignalBridge",
    title: "Revenue Operations Lead",
    phone: "+91 98760 88771",
    source: "webinar",
    stage: "cold",
    score: 12,
    temperature: "cold",
    assignedTo: "user-2",
    createdAt: "2026-03-23",
    lastActivityAt: "2026-04-10",
    nextFollowUp: "2026-04-13",
    tags: ["webinar"],
    notes: ["No engagement after webinar."],
    emailsSent: 2,
    emailsOpened: 0,
    emailsReplied: 0,
    callsMade: 0,
    callsDuration: 0,
    riskFlag: true,
    riskReason: "No response in 14 days",
    predictedWinProbability: 0.05,
    value: 5000,
  },
];
